#' bcbreader
#'
#' This function reads bcbio output.
#' @keywords dataLoading
#' @param projectDir path to final bcbio project folder. Normally
#'   named with date format.
#' @export
#' @examples
#' bcbreader()

bcbreader <- function(projectDir){
    library(dplyr)
    projectDir <- normalizePath(projectDir)
    sampleMetadata <- read.csv(file.path(projectDir,"metadata.csv"),row.names = 1)
    metrics <- import(file.path(projectDir,"multiqc","multiqc_data","multiqc_bcbio_metrics.txt"))
    metrics <- janitor::clean_names(metrics,case = "small_camel")
    sampleDirs = file.path(projectDir,"..", rownames(sampleMetadata))
    tx2genes_file <- file.path(projectDir,"tx2gene.csv")
    salmon_files = file.path(sampleDirs, "salmon", "quant.sf")
    sf_files = salmon_files
    names(sf_files) = rownames(sampleMetadata)
    # FIX check files exists and match sampleMetadata
    tx2gene = read.csv(tx2genes_file, sep=",", row.names=NULL, header=FALSE)
    txi.salmon = tximport(sf_files,
                          type="salmon",
                          tx2gene=tx2gene,
                          countsFromAbundance="lengthScaledTPM")
    rawCounts = round(data.frame(txi.salmon$counts, check.names=FALSE),0) %>%
        as.matrix()
    colData <- sampleMetadata %>% as.data.frame() %>%
        .[colnames(rawCounts),, drop = FALSE] %>%
        rownames_to_column() %>%
        mutate_all(as.factor) %>%
        mutate_all(droplevels) %>%
        column_to_rownames() %>%
        as("data.frame")

    metadata <- list(metrics = metrics,
                     countsFromAbundance = txi.salmon$countsFromAbundance)
    se <- SummarizedExperiment(assays = list(raw = rawCounts,
                                             tpm = txi.salmon$abundance,
                                             length = txi.salmon$length),
                               colData = colData,
                               metadata = metadata)
    invisible(se)
}

#' Normalize SummarizedExperiment from bcbreder function.
#' 
#' This function will detect if the object contains the slots from
#' salmon quantification or featureCounts and normalize the data
#' using DESeq2. It will update raw, normalized and vst slots in a 
#' SummarizedExperiment object.
#' 
#' @param se SummarizedExperiment object generated by readBCBIO.
#' @examples
#' data(se)
#' bcbrun(se, design = ~condition)
#' @export
bcbrun <- function(se, design = ~1){

    stopifnot(class(se) == "SummarizedExperiment")
    
    if (sum(c("length", "tpm")  %in% names(assays(se))) == 2){
        message("Using tximport data.")
        txi <- list(abundance = assays(se)[["tpm"]],
                    counts = assays(se)[["raw"]],
                    length = assays(se)[["length"]],
                    countsFromAbundance = metadata(se)[["countsFromAbundance"]])
        dds <- DESeqDataSetFromTximport(txi, colData(se), design = design) %>% 
            DESeq()
        vst <- varianceStabilizingTransformation(dds)

    }else{
        message("Using raw count assay in se object.")
        dds <- DESeqDataSetFromTximport(assay(se),
                                        colData(se),
                                        design = design) %>% 
            DESeq()
        vst <- varianceStabilizingTransformation(dds)
    }
    assays(se)[["raw"]] <-counts(dds)
    assays(se)[["normalized"]] <- counts(dds, normalized = TRUE)
    assays(se)[["vst"]] <- assay(vst)
    se
}

